### ISSUE TITLE
TODO list for the sprint

### ISSUE THREAD

**Issue by manulera** [manulera/ShareYourCloning_frontend#2]
Hello @ikayz just adding some stuff here that I will try to get done these days:

- [x] Document functions
- [x] Manage unique identifiers in the frontend
- [x] Allow to start a parallel branch of the tree
- [x] Add a source that takes two inputs, to see what it would look
- [x] Support that you can export the state of the app as json, but also import a json file with the state
- [x] Maintain the information after submission on restriction enzymes and genebank id 
- [x] Display the "show in main editor" box only in entities and source that support it.
- [x] Improve readme further

**Comment by manulera** [comment]
Just adding some ideas that came up that could be added to the frontend interface:

* Each node could have an x or dustbin icon somewhere,  to delete this node and all its children.
* The tickbox to see the sequence in the main editor could be placed better in the node, rather than just at the bottom.
* The 'add source' button could be coming down from the node, as a child node, instead of being inside the node.
